name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Test application
        run: npm test

      - name: Set up electron-builder
        uses: samuelmeuli/action-electron-builder@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish application
        run: npm run release